import { UtilityType } from '../types/bill';

export interface ProviderInfo {
  code: string;
  name: string;
  fullName: string;
  type: UtilityType;
  region: string;
  refLength: number;
  refPlaceholder: string;
  badgeColor: string;
  iconName: string;
  portalUrl: string;
  officialSite: string;
}

export const ELECTRICITY_PROVIDERS: ProviderInfo[] = [
  {
    code: 'LESCO',
    name: 'LESCO',
    fullName: 'Lahore Electric Supply Company',
    type: 'electricity',
    region: 'Lahore, Kasur, Okara, Sheikhupura',
    refLength: 14,
    refPlaceholder: '01 11512 0000000 U',
    badgeColor: '#059669',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/lescobill',
    officialSite: 'https://www.lesco.gov.pk/',
  },
  {
    code: 'MEPCO',
    name: 'MEPCO',
    fullName: 'Multan Electric Power Company',
    type: 'electricity',
    region: 'Multan, Bahawalpur, D.G. Khan, Sahiwal',
    refLength: 14,
    refPlaceholder: '14 15121 0000000 U',
    badgeColor: '#2563EB',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/mepcobill',
    officialSite: 'https://mepco.com.pk/',
  },
  {
    code: 'IESCO',
    name: 'IESCO',
    fullName: 'Islamabad Electric Supply Company',
    type: 'electricity',
    region: 'Islamabad, Rawalpindi, Attock, Jhelum',
    refLength: 14,
    refPlaceholder: '04 14121 0000000 U',
    badgeColor: '#7C3AED',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/iescobill',
    officialSite: 'https://iesco.com.pk/',
  },
  {
    code: 'FESCO',
    name: 'FESCO',
    fullName: 'Faisalabad Electric Supply Company',
    type: 'electricity',
    region: 'Faisalabad, Sargodha, Mianwali, Jhang',
    refLength: 14,
    refPlaceholder: '08 13121 0000000 U',
    badgeColor: '#D97706',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/fescobill',
    officialSite: 'https://fesco.com.pk/',
  },
  {
    code: 'GEPCO',
    name: 'GEPCO',
    fullName: 'Gujranwala Electric Power Company',
    type: 'electricity',
    region: 'Gujranwala, Sialkot, Gujrat, Hafizabad',
    refLength: 14,
    refPlaceholder: '12 12121 0000000 U',
    badgeColor: '#0D9488',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/gepcobill',
    officialSite: 'https://gepco.com.pk/',
  },
  {
    code: 'PESCO',
    name: 'PESCO',
    fullName: 'Peshawar Electric Supply Company',
    type: 'electricity',
    region: 'Peshawar, Mardan, Swat, Abbottabad',
    refLength: 14,
    refPlaceholder: '16 11121 0000000 U',
    badgeColor: '#DC2626',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/pescobill',
    officialSite: 'https://pesco.com.pk/',
  },
  {
    code: 'HESCO',
    name: 'HESCO',
    fullName: 'Hyderabad Electric Supply Company',
    type: 'electricity',
    region: 'Hyderabad, Mirpurkhas, Nawabshah',
    refLength: 14,
    refPlaceholder: '20 18121 0000000 U',
    badgeColor: '#4F46E5',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/hescobill',
    officialSite: 'https://hesco.gov.pk/',
  },
  {
    code: 'SEPCO',
    name: 'SEPCO',
    fullName: 'Sukkur Electric Power Company',
    type: 'electricity',
    region: 'Sukkur, Larkana, Ghotki, Jacobabad',
    refLength: 14,
    refPlaceholder: '24 17121 0000000 U',
    badgeColor: '#EA580C',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/sepcobill',
    officialSite: 'https://sepco.com.pk/',
  },
  {
    code: 'QESCO',
    name: 'QESCO',
    fullName: 'Quetta Electric Supply Company',
    type: 'electricity',
    region: 'Quetta, Gwadar, Khuzdar, Sibi',
    refLength: 14,
    refPlaceholder: '28 16121 0000000 U',
    badgeColor: '#0284C7',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/qescobill',
    officialSite: 'https://qesco.com.pk/',
  },
  {
    code: 'TESCO',
    name: 'TESCO',
    fullName: 'Tribal Electric Supply Company',
    type: 'electricity',
    region: 'Khyber, Bajaur, Mohmand, Waziristan',
    refLength: 14,
    refPlaceholder: '30 19121 0000000 U',
    badgeColor: '#475569',
    iconName: 'flash',
    portalUrl: 'https://bill.pitc.com.pk/tescobill',
    officialSite: 'https://tesco.gov.pk/',
  },
  {
    code: 'KELECTRIC',
    name: 'K-Electric',
    fullName: 'K-Electric Karachi',
    type: 'electricity',
    region: 'Karachi, Dhabeji, Gharo, Hub',
    refLength: 13,
    refPlaceholder: '0400012345678',
    badgeColor: '#16A34A',
    iconName: 'flash',
    portalUrl: 'https://www.ke.com.pk/customer-services/bill-and-e-services/',
    officialSite: 'https://www.ke.com.pk/',
  },
];

export const GAS_PROVIDERS: ProviderInfo[] = [
  {
    code: 'SNGPL',
    name: 'SNGPL',
    fullName: 'Sui Northern Gas Pipelines Ltd',
    type: 'gas',
    region: 'Punjab, Khyber Pakhtunkhwa, AJK, Islamabad',
    refLength: 11,
    refPlaceholder: '12345678901',
    badgeColor: '#0284C7',
    iconName: 'flame',
    portalUrl: 'https://www.sngpl.com.pk/',
    officialSite: 'https://www.sngpl.com.pk/',
  },
  {
    code: 'SSGC',
    name: 'SSGC',
    fullName: 'Sui Southern Gas Company',
    type: 'gas',
    region: 'Sindh, Balochistan, Karachi',
    refLength: 10,
    refPlaceholder: '1234567890',
    badgeColor: '#E11D48',
    iconName: 'flame',
    portalUrl: 'https://www.ssgc.com.pk/web/',
    officialSite: 'https://www.ssgc.com.pk/',
  },
];

export const ALL_PROVIDERS: ProviderInfo[] = [
  ...ELECTRICITY_PROVIDERS,
  ...GAS_PROVIDERS,
];
