import { StyleSheet, Dimensions } from 'react-native';

const { height: SCREEN_H } = Dimensions.get('window');

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  sheet: {
    height: SCREEN_H * 0.88,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#4B5563',
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 4,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  backBtn: { padding: 4, minWidth: 60 },
  backBtnText: { fontSize: 14, fontWeight: '700' },
  sheetTitle: { fontSize: 16, fontWeight: '800', flex: 1, textAlign: 'center' },
  closeBtn: { padding: 4, minWidth: 28, alignItems: 'flex-end' },
  closeBtnText: { fontSize: 18, fontWeight: '600' },
  stepContent: { flex: 1, paddingHorizontal: 16, paddingTop: 12 },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    height: 44,
    marginBottom: 12,
  },
  searchInput: { flex: 1, fontSize: 14, fontWeight: '500' },
  groupLabel: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginBottom: 6,
    marginLeft: 2,
  },
  providerList: { flex: 1 },
  providerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 8,
    gap: 12,
  },
  providerDot: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
  },
  providerDotText: { color: '#FFF', fontWeight: '800', fontSize: 12 },
  providerRowInfo: { flex: 1 },
  providerRowName: { fontSize: 14, fontWeight: '800' },
  providerRowSub: { fontSize: 11, marginTop: 1 },
  providerRowArrow: { fontSize: 22, fontWeight: '600' },
  selectedProviderBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 16,
    marginBottom: 20,
  },
  selectedProvName: { fontSize: 20, fontWeight: '800' },
  selectedProvFull: { fontSize: 12, marginTop: 2 },
  fieldLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 0.5, marginBottom: 6, marginLeft: 2 },
  toggleRow: {
    flexDirection: 'row',
    borderRadius: 12,
    borderWidth: 1,
    padding: 4,
    gap: 4,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 9,
    alignItems: 'center',
  },
  toggleBtnText: { fontSize: 13, fontWeight: '700' },
  modernInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1.5,
    paddingHorizontal: 14,
    height: 54,
    gap: 10,
  },
  modernInputIcon: { fontSize: 18, fontWeight: '600' },
  modernInput: { flex: 1, fontSize: 16, fontWeight: '600', letterSpacing: 0.5 },
  inputHint: { fontSize: 11, marginTop: 5, marginLeft: 4 },
  saveBtn: {
    marginTop: 24,
    height: 54,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveBtnText: { color: '#FFF', fontSize: 16, fontWeight: '800' },
  savingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
