import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  heroWrapper: {
    backgroundColor: '#0C2B4E',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 28,
    position: 'relative',
    overflow: 'hidden',
  },
  circuitDecoration: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    zIndex: 1,
    overflow: 'hidden',
  },
  circuitLine: {
    width: 1.5,
    height: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    position: 'relative',
    overflow: 'hidden',
  },
  currentPulseStream: {
    position: 'absolute',
    top: 0,
    left: -1.25,
    width: 4,
    height: 44,
    borderRadius: 2,
    backgroundColor: '#62FF96',
    shadowColor: '#62FF96',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  electricSparkHead: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 6,
    marginBottom: -1,
  },
  heroContent: {
    zIndex: 10,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  rtlRow: {
    flexDirection: 'row-reverse',
  },
  greetingCol: {
    flex: 1,
  },
  greetingText: {
    fontSize: 21,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  subLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
    gap: 6,
  },
  locationTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  locationText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#62FF96',
    letterSpacing: 0.3,
  },
  syncDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#3FFF8B',
  },
  syncText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionCircleBtn: {
    paddingHorizontal: 10,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#213145',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  notificationBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#213145',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  unreadGreenDot: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#62FF96',
    borderWidth: 1.5,
    borderColor: '#0C2B4E',
  },
  bentoCard: {
    backgroundColor: '#0F2238',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(98, 255, 150, 0.40)',
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#62FF96',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.20,
    shadowRadius: 14,
    elevation: 6,
  },
  bentoTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  bentoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  bentoAmount: {
    fontSize: 26,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  unpaidBadge: {
    backgroundColor: '#059669',
    paddingHorizontal: 10,
    paddingVertical: 4.5,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  unpaidPingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  unpaidBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  rtlText: {
    textAlign: 'right',
  },
});
