import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    height: '94%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
  },
  modalDark: {
    backgroundColor: '#0F172A',
  },
  modalLight: {
    backgroundColor: '#F8FAFC',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: '#004D25',
  },
  headerTitleGroup: {
    flex: 1,
  },
  verifiedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  pulseDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#62FF96',
    marginRight: 6,
  },
  verifiedText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#62FF96',
    letterSpacing: 0.5,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  headerRefText: {
    fontSize: 11,
    color: '#D1E7DD',
    marginTop: 1,
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  actionToolbar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  toolbarDark: {
    backgroundColor: '#1E293B',
    borderBottomColor: '#334155',
  },
  toolbarLight: {
    backgroundColor: '#FFFFFF',
    borderBottomColor: '#E2E8F0',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.06)',
    borderRadius: 10,
    padding: 3,
    width: '100%',
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 8,
  },
  tabButtonActiveDark: {
    backgroundColor: '#006D35',
  },
  tabButtonActiveLight: {
    backgroundColor: '#006D35',
  },
  tabButtonText: {
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 6,
  },
  tabButtonTextActive: {
    color: '#FFFFFF',
  },
  tabDarkText: {
    color: '#94A3B8',
  },
  tabLightText: {
    color: '#64748B',
  },
  bottomFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    gap: 12,
  },
  bottomFooterDark: {
    backgroundColor: '#1E293B',
    borderTopColor: '#334155',
  },
  bottomFooterLight: {
    backgroundColor: '#FFFFFF',
    borderTopColor: '#E2E8F0',
  },
  savePdfBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#006D35',
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 10,
    gap: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  savePdfBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  shareIconButton: {
    width: 48,
    height: 48,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
  },
  shareIconDark: {
    backgroundColor: 'rgba(98, 255, 150, 0.12)',
    borderColor: '#006D35',
  },
  shareIconLight: {
    backgroundColor: '#F0FDF4',
    borderColor: '#86EFAC',
  },
  downloadSuccessBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
  },
  downloadSuccessDark: {
    backgroundColor: '#064E3B',
    borderTopColor: '#047857',
  },
  downloadSuccessLight: {
    backgroundColor: '#DCFCE7',
    borderTopColor: '#BBF7D0',
  },
  downloadSuccessLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  downloadSuccessText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#065F46',
  },
  viewDownloadedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#006D35',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    gap: 6,
  },
  viewDownloadedBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  webViewWrapper: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  webView: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  fallbackSummaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#006D35',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 8,
    marginTop: 14,
  },
  fallbackSummaryBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  textDark: {
    color: '#F1F5F9',
  },
  textLight: {
    color: '#1E293B',
  },
  billDocumentContainer: {
    padding: 12,
    paddingBottom: 40,
  },
  billDocumentSheet: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 12,
  },
  sheetDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  sheetLight: {
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
  },
  sheetHeader: {
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingBottom: 10,
    marginBottom: 10,
  },
  sheetMainTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: '#006D35',
    textAlign: 'center',
  },
  sheetSubTitle: {
    fontSize: 9,
    fontWeight: '700',
    color: '#64748B',
    marginTop: 2,
    letterSpacing: 0.5,
  },
  sheetStampBadge: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 6,
  },
  sheetStampText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#166534',
    letterSpacing: 0.5,
  },
  sheetAmountBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  sheetLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#166534',
  },
  sheetAmountVal: {
    fontSize: 20,
    fontWeight: '900',
    color: '#166534',
    marginTop: 2,
  },
  statusChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  statusUnpaid: {
    backgroundColor: '#FEE2E2',
  },
  statusPaid: {
    backgroundColor: '#DCFCE7',
  },
  statusUnpaidText: {
    color: '#991B1B',
    fontWeight: '800',
    fontSize: 11,
  },
  statusPaidText: {
    color: '#166534',
    fontWeight: '800',
    fontSize: 11,
  },
  sheet2ColGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sheetInfoBox: {
    width: '48%',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  sheetBoxLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#64748B',
  },
  sheetBoxVal: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 2,
  },
  tableBlock: {
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    marginBottom: 10,
  },
  tableHeaderBar: {
    backgroundColor: '#0F172A',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  tableHeaderTitle: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
  },
  tableCellLabel: {
    fontSize: 11,
    color: '#475569',
  },
  tableCellVal: {
    fontSize: 11,
    color: '#0F172A',
  },
  tableCellValBold: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0F172A',
  },
  tableCellMono: {
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: '700',
    color: '#0F172A',
  },
  tableCellNum: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0F172A',
  },
  barcodeSection: {
    padding: 10,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
  },
  barcodeTitle: {
    fontSize: 9,
    fontWeight: '700',
    color: '#64748B',
  },
  barcodeBox: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderRadius: 4,
    marginTop: 4,
  },
  barcodeText: {
    fontFamily: 'monospace',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2,
    color: '#0F172A',
  },
});
