import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F1C2C',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  glowBgTop: {
    position: 'absolute',
    width: 380,
    height: 380,
    borderRadius: 190,
    backgroundColor: 'rgba(0, 131, 246, 0.08)',
    top: height * 0.15,
    left: width * 0.5 - 190,
  },
  glowBgBottom: {
    position: 'absolute',
    width: 440,
    height: 440,
    borderRadius: 220,
    backgroundColor: 'rgba(98, 255, 150, 0.06)',
    bottom: height * 0.1,
    left: width * 0.5 - 220,
  },
  circuitSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.25,
  },
  header: {
    width: '100%',
    paddingTop: 36,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 10,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 27, 60, 0.85)',
    borderColor: 'rgba(116, 119, 125, 0.35)',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    gap: 6,
  },
  pulseDotWrapper: {
    width: 8,
    height: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pulseDotOuter: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#00E475',
    opacity: 0.6,
  },
  pulseDotInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#62FF96',
  },
  statusText: {
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '700',
    color: '#62FF96',
    letterSpacing: 0.6,
  },
  gridBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  gridText: {
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '600',
    color: '#778598',
    letterSpacing: 0.5,
  },
  centerContent: {
    width: '100%',
    maxWidth: 340,
    paddingHorizontal: 20,
    alignItems: 'center',
    zIndex: 10,
    marginVertical: 'auto',
  },
  emblemWrapper: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  emblemGlow: {
    position: 'absolute',
    width: 140,
    height: 170,
    borderRadius: 24,
    backgroundColor: 'rgba(98, 255, 150, 0.12)',
  },
  billInvoiceSlate: {
    width: 138,
    height: 162,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderColor: '#C7D9EC',
    borderWidth: 1.5,
    overflow: 'hidden',
    justifyContent: 'space-between',
  },
  invoiceHeader: {
    backgroundColor: '#0C2B4E',
    paddingVertical: 5,
    paddingHorizontal: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1.5,
    borderBottomColor: '#006D35',
  },
  invoiceHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  invoiceHeaderTitle: {
    fontFamily: 'monospace',
    fontSize: 8.5,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.4,
  },
  invoiceHeaderBadge: {
    backgroundColor: 'rgba(98, 255, 150, 0.2)',
    borderColor: '#62FF96',
    borderWidth: 0.6,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
  },
  invoiceHeaderBadgeText: {
    fontFamily: 'monospace',
    fontSize: 7,
    fontWeight: '800',
    color: '#62FF96',
  },
  invoiceSubHeader: {
    backgroundColor: '#F1F5F9',
    paddingVertical: 2.5,
    paddingHorizontal: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E2E8F0',
    alignItems: 'center',
  },
  invoiceCompanyText: {
    fontSize: 7.5,
    fontWeight: '700',
    color: '#475569',
    letterSpacing: 0.3,
  },
  invoiceBarcodeSection: {
    paddingHorizontal: 8,
    paddingTop: 4,
    alignItems: 'center',
    gap: 2.5,
  },
  barcodeVisual: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingHorizontal: 6,
  },
  barLine: {
    backgroundColor: '#1E293B',
    borderRadius: 0.5,
  },
  invoiceRefText: {
    fontFamily: 'monospace',
    fontSize: 7.5,
    fontWeight: '700',
    color: '#0F172A',
    letterSpacing: 0.5,
  },
  invoiceStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    marginHorizontal: 6,
    paddingVertical: 3.5,
    paddingHorizontal: 6,
    borderRadius: 6,
    borderWidth: 0.8,
    borderColor: '#E2E8F0',
  },
  invoiceStatCol: {
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 6.5,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.2,
  },
  statVal: {
    fontFamily: 'monospace',
    fontSize: 8,
    fontWeight: '800',
    color: '#0F172A',
  },
  statAmount: {
    fontFamily: 'monospace',
    fontSize: 8.5,
    fontWeight: '900',
    color: '#006D35',
  },
  invoiceDividerVertical: {
    width: 1,
    height: 14,
    backgroundColor: '#CBD5E1',
  },
  invoiceBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    paddingBottom: 10,
    gap: 4,
  },
  miniUtilityChipZap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    backgroundColor: '#E8F5E9',
    borderColor: '#A5D6A7',
    borderWidth: 0.6,
    borderRadius: 4,
    paddingVertical: 2,
  },
  miniChipZapText: {
    fontSize: 7,
    fontWeight: '800',
    color: '#1B5E20',
  },
  miniUtilityChipFlame: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    backgroundColor: '#FFF7ED',
    borderColor: '#FFEDD5',
    borderWidth: 0.6,
    borderRadius: 4,
    paddingVertical: 2,
  },
  miniChipFlameText: {
    fontSize: 7,
    fontWeight: '800',
    color: '#C2410C',
  },
  techBadgePin: {
    position: 'absolute',
    bottom: -10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#0F1C2C',
    borderColor: '#62FF96',
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2.5,
    borderRadius: 999,
    shadowColor: '#62FF96',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 6,
  },
  techBadgeText: {
    fontFamily: 'monospace',
    fontSize: 9,
    fontWeight: '800',
    color: '#62FF96',
    letterSpacing: 0.5,
  },
  appTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 14,
  },
  appTitleMain: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  appTitleAccent: {
    fontSize: 28,
    fontWeight: '900',
    color: '#62FF96',
    letterSpacing: -0.5,
    marginLeft: 4,
  },
  appSubtitle: {
    fontSize: 13,
    fontWeight: '500',
    color: '#778598',
    marginTop: 3,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 6,
    marginTop: 18,
    opacity: 0.85,
  },
  chip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: 'rgba(0, 27, 60, 0.9)',
    borderColor: 'rgba(116, 119, 125, 0.3)',
    borderWidth: 1,
  },
  chipText: {
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '600',
    color: '#778598',
  },
  footer: {
    width: '100%',
    maxWidth: 340,
    paddingHorizontal: 20,
    paddingBottom: 36,
    alignItems: 'center',
    zIndex: 10,
  },
  progressWrapper: {
    width: '100%',
    marginBottom: 14,
  },
  progressLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  progressLabel: {
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '600',
    color: '#778598',
  },
  progressPercent: {
    fontFamily: 'monospace',
    fontSize: 11,
    fontWeight: '800',
    color: '#62FF96',
  },
  progressBarTrack: {
    width: '100%',
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(211, 228, 254, 0.15)',
    overflow: 'hidden',
    borderColor: 'rgba(116, 119, 125, 0.3)',
    borderWidth: 1,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: '#00E475',
    shadowColor: '#62FF96',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
  },
  attributionRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: 'rgba(116, 119, 125, 0.2)',
    paddingTop: 10,
  },
  brandByText: {
    fontSize: 12,
    color: '#778598',
  },
  brandNameText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.2,
  },
  versionCapsule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: '#001B3C',
    borderColor: 'rgba(116, 119, 125, 0.35)',
    borderWidth: 1,
  },
  versionText: {
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '700',
    color: '#62FF96',
  },
});
